---
# tasks file for letsencrypt

- name: Manage user accounts
  user:
    name: letsencrypt
    groups: ssl-cert
    system: true
    state: present
  tags:
    - setup
    - letsencrypt

- name: Install package requirements
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ letsencrypt_packages }}"
    - "{{ letsencrypt_additional_packages }}"
  tags:
    - package
    - letsencrypt

- name: Install pip requirements
  pip:
    name: "{{ item }}"
    executable: /usr/bin/pip
    state: present
  with_items:
    - "{{ letsencrypt_pip_packages }}"
    - "{{ letsencrypt_additional_pip_packages }}"
  tags:
    - package
    - letsencrypt

- name: Create config directory
  file:
    path: "{{ item }}"
    owner: letsencrypt
    group: ssl-cert
    mode: 0755
    state: directory
  with_items:
    - /etc/letsencrypt
    - /var/lib/letsencrypt
    - /var/log/letsencrypt
  tags:
    - setup
    - letsencrypt

- name: Configure letsencrypt
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: letsencrypt
    group: ssl-cert
    mode: "{{ item.mode }}"
  with_items:
    - "{{ letsencrypt_config_files }}"
  no_log: true
  tags:
    - config
    - letsencrypt
