---
- name: Converge
  hosts: all
  vars:
    letsencrypt_config_files:
      - { src: 'cli.ini.j2', dest: '/etc/letsencrypt/cli.ini', mode: '0644' }
    letsencrypt_email: test@example.com
    letsencrypt_domains:
      - example.com
  roles:
    - role: letsencrypt
